### ISSUE TITLE
how to compile on ubuntu 18.04

### ISSUE THREAD

**Issue by shomedas** [adrelino/mv-lm-icp#8]
I am trying to compile your code for ubuntu 18.04. It get the following windows related compilation error:

~/mv-lm-icp/include/dirent.h:19:10: fatal error: windows.h: No such file or directory
 #include <windows.h>

I tried to comment windows.h in dirent.h. But may other errors related to windows started popping up.
How do I remove these windows related errors? Is there any old commit that works fine with linux/ubuntu?

**Comment by aravindbattaje** [comment]
Use the [compile-on-linux](https://github.com/adrelino/mv-lm-icp/tree/compile-on-linux) branch
